import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Bingo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen w-screen overflow-hidden"
      >
        {children}
      </body>
    </html>
  );
}
